### ISSUE TITLE
Scan card feature crashes

### ISSUE THREAD

**Issue by smihajlovski** [wirecard/paymentSDK-Android#10]
Hello,

I've followed the instructions [here](https://document-center.wirecard.com/display/PTD/Basic+Setup+and+Integration) for enabling the `scan` feature. I've tested in on different Android versions and emulator/device. I've also done the same to the test project and I always get the same error:

`java.lang.NoClassDefFoundError: Failed resolution of: Lio/card/payment/CardIOActivity;
    at de.wirecard.paymentsdk.helpers.CardScannerHelper.createCardScannerIntent(Unknown Source)
    at de.wirecard.paymentsdk.ui.fragment.CardFragment.b(Unknown Source)
    at de.wirecard.paymentsdk.ui.fragment.CardFragment.startScanner(Unknown Source)
    at de.wirecard.paymentsdk.ui.presenter.CardPresenterImpl.onScanButtonClicked(Unknown Source)
    at de.wirecard.paymentsdk.ui.fragment.CardFragment$8.onClick(Unknown Source)
    at android.view.View.performClick(View.java:5637)
    at android.view.View$PerformClick.run(View.java:22429)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6119)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
    Caused by: java.lang.ClassNotFoundException: Didn't find class "io.card.payment.CardIOActivity" on path: DexPathList[[zip file "/data/app//base.apk"],nativeLibraryDirectories=[/data/app/-2/lib/x86, /data/app/-2/base.apk!/lib/x86, /system/lib, /vendor/lib]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    at de.wirecard.paymentsdk.helpers.CardScannerHelper.createCardScannerIntent(Unknown Source) 
    at de.wirecard.paymentsdk.ui.fragment.CardFragment.b(Unknown Source) 
    at de.wirecard.paymentsdk.ui.fragment.CardFragment.startScanner(Unknown Source) 
    at de.wirecard.paymentsdk.ui.presenter.CardPresenterImpl.onScanButtonClicked(Unknown Source) 
    at de.wirecard.paymentsdk.ui.fragment.CardFragment$8.onClick(Unknown Source) 
    at android.view.View.performClick(View.java:5637) 
    at android.view.View$PerformClick.run(View.java:22429) 
    at android.os.Handler.handleCallback(Handler.java:751) 
    at android.os.Handler.dispatchMessage(Handler.java:95) 
    at android.os.Looper.loop(Looper.java:154) 
    at android.app.ActivityThread.main(ActivityThread.java:6119) `

**Comment by stefan-sedlak** [comment]
Please try to use:
`compile 'io.card:android-sdk:5.5.1'`
instead
`cardIOEnabledCompile 'io.card:android-sdk:5.5.1'`

An issue may cause missing proguard rules:
>-keep class io.card.**
>-keepclassmembers class io.card.** {
>     *;
>}

**Comment by smihajlovski** [comment]
It doesn't crash anymore, but when I try to scan the card it does nothing, it's just focusing on the card. Does it need further adjustment?

**Comment by stefan-sedlak** [comment]
As you can see it uses card.io library.
It supports **embossed** cards only.
Scanning depends as well on lightning conditions.
