### ISSUE TITLE
2.14.0 crashes a multidexed app

### ISSUE THREAD

**Issue by peshkira** [wirecard/paymentSDK-Android#11]
I just updated the wirecard SDK in my multidexed app from 2.11.1 to 2.14.0 and the app crashes with the following exception as soon as I initialize Wirecard.

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/zapp/library/merchant/ui/PBBAPopupCallback;
        at de.wirecard.paymentsdk.WirecardClientBuilder.build(Unknown Source:0)
        at com.hidden.myapp_package.inject.modules.AppModule.provideWireCardClient$app_betaDebug(AppModule.kt:63)
        at com.hidden.myapp_package.inject.modules.AppModule_ProvideWireCardClient$app_betaDebugFactory.get(AppModule_ProvideWireCardClient$app_betaDebugFactory.java:29)
        at com.hidden.myapp_package.inject.modules.AppModule_ProvideWireCardClient$app_betaDebugFactory.get(AppModule_ProvideWireCardClient$app_betaDebugFactory.java:10)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.hidden.myapp_package.inject.components.DaggerAppComponent.paymentProcessor(DaggerAppComponent.java:214)
        at com.hidden.myapp_package.inject.components.DaggerActivityComponent$com_hidden_myapp_package_inject_components_AppComponent_paymentProcessor.get(DaggerActivityComponent.java:499)
        at com.hidden.myapp_package.inject.components.DaggerActivityComponent$com_hidden_myapp_package_inject_components_AppComponent_paymentProcessor.get(DaggerActivityComponent.java:488)
        at com.hidden.myapp_package.ui.main.MainViewModel_Factory.get(MainViewModel_Factory.java:34)
        at com.hidden.myapp_package.ui.main.MainViewModel_Factory.get(MainViewModel_Factory.java:11)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.hidden.myapp_package.inject.components.DaggerActivityComponent.injectMainNavigationActivity(DaggerActivityComponent.java:332)
        at com.hidden.myapp_package.inject.components.DaggerActivityComponent.inject(DaggerActivityComponent.java:263)
        at com.hidden.myapp_package.ui.main.MainNavigationActivity.onCreate(MainNavigationActivity.kt:76)
        at android.app.Activity.performCreate(Activity.java:6999)
        at android.app.Activity.performCreate(Activity.java:6990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.zapp.library.merchant.ui.PBBAPopupCallback" on path: DexPathList[[zip file "/data/app/com.hidden.myapp_package.beta-DICDLqZN4d3SwtiQx9TTtw==/base.apk"],nativeLibraryDirectories=[/data/app/com.hidden.myapp_package.beta-DICDLqZN4d3SwtiQx9TTtw==/lib/arm64, /data/app/com.hidden.myapp_package.beta-DICDLqZN4d3SwtiQx9TTtw==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at de.wirecard.paymentsdk.WirecardClientBuilder.build(Unknown Source:0) 
        at com.hidden.myapp_package.inject.modules.AppModule.provideWireCardClient$app_betaDebug(AppModule.kt:63) 
        at com.hidden.myapp_package.inject.modules.AppModule_ProvideWireCardClient$app_betaDebugFactory.get(AppModule_ProvideWireCardClient$app_betaDebugFactory.java:29) 
        at com.hidden.myapp_package.inject.modules.AppModule_ProvideWireCardClient$app_betaDebugFactory.get(AppModule_ProvideWireCardClient$app_betaDebugFactory.java:10) 
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47) 
        at com.hidden.myapp_package.inject.components.DaggerAppComponent.paymentProcessor(DaggerAppComponent.java:214) 
        at com.hidden.myapp_package.inject.components.DaggerActivityComponent$com_hidden_myapp_package_inject_components_AppComponent_paymentProcessor.get(DaggerActivityComponent.java:499) 
        at com.hidden.myapp_package.inject.components.DaggerActivityComponent$com_hidden_myapp_package_inject_components_AppComponent_paymentProcessor.get(DaggerActivityComponent.java:488) 
        at com.hidden.myapp_package.ui.main.MainViewModel_Factory.get(MainViewModel_Factory.java:34) 
        at com.hidden.myapp_package.ui.main.MainViewModel_Factory.get(MainViewModel_Factory.java:11) 
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47) 
        at com.hidden.myapp_package.inject.components.DaggerActivityComponent.injectMainNavigationActivity(DaggerActivityComponent.java:332) 
        at com.hidden.myapp_package.inject.components.DaggerActivityComponent.inject(DaggerActivityComponent.java:263) 
        at com.hidden.myapp_package.ui.main.MainNavigationActivity.onCreate(MainNavigationActivity.kt:76) 
        at android.app.Activity.performCreate(Activity.java:6999) 
        at android.app.Activity.performCreate(Activity.java:6990) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

Note, that multidex is properly enabled (following the official guide: https://developer.android.com/studio/build/multidex) and it works with the previous version of the SDK.

**UPDATE**
I have tried to downgrade all versions to check where the issue was introduced. 2.12.0 works as well and all other versions after that seem to crash with the same error.

**Comment by stefan-sedlak** [comment]
Please add external dependency according [doc](https://document-center.wirecard.com/display/PTD/Basic+Setup+and+Integration#BasicSetupandIntegration-ExternalLibraries&Other):
`compile 'com.zapp.library:merchant:1.1.0'`
