### ISSUE TITLE
   java.lang.NoClassDefFoundError: Failed resolution of: Lretrofit2/converter/simplexml/SimpleXmlConverterFactory;

### ISSUE THREAD

**Issue by anmolgupta8899** [wirecard/paymentSDK-Android#18]
Process: com.verkoopapp, PID: 31603
                                                                java.lang.NoClassDefFoundError: Failed resolution of: Lretrofit2/converter/simplexml/SimpleXmlConverterFactory;
                                                                    at de.wirecard.paymentsdk.api.ElasticApiFactory.newInstance(Unknown Source)
                                                                    at de.wirecard.paymentsdk.api.ServerApiImpl.a(Unknown Source)
                                                                    at de.wirecard.paymentsdk.api.ServerApiImpl.init(Unknown Source)
                                                                    at de.wirecard.paymentsdk.api.RestClientImpl.a(Unknown Source)
                                                                    at de.wirecard.paymentsdk.api.RestClientImpl.<init>(Unknown Source)
                                                                    at de.wirecard.paymentsdk.a.initRestApi(Unknown Source)
                                                                    at de.wirecard.paymentsdk.a.checkPayment(Unknown Source)
                                                                    at com.verkoopapp.activity.MyWalletActivity$setData$2.onClick(MyWalletActivity.kt:107)
                                                                    at android.view.View.performClick(View.java:5204)
                                                                    at android.view.View$PerformClick.run(View.java:21153)
                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                 Caused by: java.lang.ClassNotFoundException: Didn't find class "retrofit2.converter.simplexml.SimpleXmlConverterFactory" on path: DexPathList[[zip file "/data/app/com.verkoopapp-2/base.apk"],nativeLibraryDirectories=[/data/app/com.verkoopapp-2/lib/arm, /data/app/com.verkoopapp-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
                                                                    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                    at de.wirecard.paymentsdk.api.ElasticApiFactory.newInstance(Unknown Source) 
                                                                    at de.wirecard.paymentsdk.api.ServerApiImpl.a(Unknown Source) 
                                                                    at de.wirecard.paymentsdk.api.ServerApiImpl.init(Unknown Source) 
                                                                    at de.wirecard.paymentsdk.api.RestClientImpl.a(Unknown Source) 
                                                                    at de.wirecard.paymentsdk.api.RestClientImpl.<init>(Unknown Source) 
                                                                    at de.wirecard.paymentsdk.a.initRestApi(Unknown Source) 
                                                                    at de.wirecard.paymentsdk.a.checkPayment(Unknown Source) 
                                                                    at com.verkoopapp.activity.MyWalletActivity$setData$2.onClick(MyWalletActivity.kt:107) 
                                                                    at android.view.View.performClick(View.java:5204) 
                                                                    at android.view.View$PerformClick.run(View.java:21153) 
                                                                    at android.os.Handler.handleCallback(Handler.java:739) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                    at android.os.Looper.loop(Looper.java:148) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                	Suppressed: java.lang.ClassNotFoundException: retrofit2.converter.simplexml.SimpleXmlConverterFactory
                                                                    at java.lang.Class.classForName(Native Method)
                                                                    at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                    at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                    		... 18 more
                                                                 Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by stefan-sedlak** [comment]
Hi @anmolgupta8899 ,
it seems you integrate 2.x version.
You can integrate the most recent version: http://wirecard.github.io/paymentSDK-Android/integration/latest/

**Comment by stefan-sedlak** [comment]
If you need help please (re)open the issue
