### ISSUE TITLE
Proguard and reflection.  java.lang.AssertionError: java.lang.NoSuchFieldException: SUCCESS

### ISSUE THREAD

**Issue by santikrass** [wirecard/paymentSDK-Android#2]
Adding this rule solve the issue:

-keep public class de.wirecard.paymentsdk.** {
  public protected *;
}

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.flyersconcierge.tracker, PID: 30217
                  java.lang.AssertionError: java.lang.NoSuchFieldException: SUCCESS
                      at com.google.gson.b.a.n$a.<init>(TypeAdapters.java:808)
                      at com.google.gson.b.a.n$24.a(TypeAdapters.java:834)
                      at com.google.gson.f.a(Gson.java:423)
                      at com.google.gson.b.a.i.a(ReflectiveTypeAdapterFactory.java:3115)
                      at com.google.gson.b.a.i.a(ReflectiveTypeAdapterFactory.java:100)
                      at com.google.gson.f.a(Gson.java:423)
                      at com.google.gson.b.a.i.a(ReflectiveTypeAdapterFactory.java:3115)
                      at com.google.gson.b.a.i.a(ReflectiveTypeAdapterFactory.java:100)
                      at com.google.gson.f.a(Gson.java:423)
                      at b.a.a.a.a(GsonConverterFactory.java:63)
                      at de.wirecard.paymentsdk.api.a.a(SourceFile:30)
                      at b.n$a.b(ServiceMethod.java:8325)
                      at b.m.a(Retrofit.java:1167)
                      at b.m$1.invoke(Retrofit.java:145)
                      at $Proxy19.makeTransaction(Native Method)
                      at de.wirecard.paymentsdk.ui.activity.PaymentActivity.a(SourceFile:274)
                      at de.wirecard.paymentsdk.ui.a.b.a(SourceFile:336)
                      at de.wirecard.paymentsdk.ui.a.b.g(SourceFile:43)
                      at de.wirecard.paymentsdk.ui.a.b$3.onClick(SourceFile:217)
                      at android.view.View.performClick(View.java:4438)
                      at android.view.View$PerformClick.run(View.java:18422)
                      at android.os.Handler.handleCallback(Handler.java:733)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:136)
                      at android.app.ActivityThread.main(ActivityThread.java:5001)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                      at dalvik.system.NativeStart.main(Native Method)
                   Caused by: java.lang.NoSuchFieldException: SUCCESS
                      at java.lang.Class.getField(Class.java:724)
                      at com.google.gson.b.a.n$a.<init>(TypeAdapters.java:797)
                      at com.google.gson.b.a.n$24.a(TypeAdapters.java:834) 
                      at com.google.gson.f.a(Gson.java:423) 
                      at com.google.gson.b.a.i.a(ReflectiveTypeAdapterFactory.java:3115) 
                      at com.google.gson.b.a.i.a(ReflectiveTypeAdapterFactory.java:100) 
                      at com.google.gson.f.a(Gson.java:423) 
                      at com.google.gson.b.a.i.a(ReflectiveTypeAdapterFactory.java:3115) 
                      at com.google.gson.b.a.i.a(ReflectiveTypeAdapterFactory.java:100) 
                      at com.google.gson.f.a(Gson.java:423) 
                      at b.a.a.a.a(GsonConverterFactory.java:63) 
                      at de.wirecard.paymentsdk.api.a.a(SourceFile:30) 
                      at b.n$a.b(ServiceMethod.java:8325) 
                      at b.m.a(Retrofit.java:1167) 
                      at b.m$1.invoke(Retrofit.java:145) 
                      at $Proxy19.makeTransaction(Native Method) 
                      at de.wirecard.paymentsdk.ui.activity.PaymentActivity.a(SourceFile:274) 
                      at de.wirecard.paymentsdk.ui.a.b.a(SourceFile:336) 
                      at de.wirecard.paymentsdk.ui.a.b.g(SourceFile:43) 
                      at de.wirecard.paymentsdk.ui.a.b$3.onClick(SourceFile:217) 
                      at android.view.View.performClick(View.java:4438) 
                      at android.view.View$PerformClick.run(View.java:18422) 
                      at android.os.Handler.handleCallback(Handler.java:733) 
                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                      at android.os.Looper.loop(Looper.java:136) 
                      at android.app.ActivityThread.main(ActivityThread.java:5001) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:515) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                      at dalvik.system.NativeStart.main(Native Method)

**Comment by PaymentSDK** [comment]
Hi, it will be fixed in next release.

**Comment by smihajlovski** [comment]
Hi @PaymentSDK I've added both 
`-keep class io.card.**
-keepclassmembers class io.card.** {*;}` and 
`-keep public class de.wirecard.paymentsdk.** {
public protected *;
}` and the app does not crash anymore but I get the following error now:

![wc proguard](https://user-images.githubusercontent.com/24569255/39628948-e00a85f6-4faa-11e8-8bc5-417c2c0f358c.png)
